main: me.goodgamer123.ServerSpawn.MainClass
api-version: 1.17
name: ServerSpawn
author: goodgamer123
description: config the spawn location and join and leave messages.
version: 3.1.0

commands:
  serverspawn:
    description: config the serverspawn.
    permission: serverspawn.serverspawn
  lobby:
    description: teleport to the spawn.
  hub:
    description: teleport to the spawn.
  spawn:
    description: teleport to the spawn.
  fake:
    description: fake your join or leave.
    permission: serverspawn.fake
  leavemessage:
    description: config the leavemessage.
    permission: serverspawn.leavemessage
  joinmessage:
    description: config the joinmessage.
    permission: serverspawn.joinmessage
  colorcodes:
    description: get a list of the minecraft colorcodes.
    permission: serverspawn.colorcodes
  custommessages:
    descriptoin: enable and disable the custom messages.
    permission: serverspawn.custommessages
  spawncommands:
    descriptoin: enable and disable spawn commands.
    permission: serverspawn.custommessages
  respawnatserverspawn:
    descriptoin: enable and disable respawn at server spawn.
    permission: serverspawn.respawnatserverspawn